# Generated by Django 5.2.7 on 2025-11-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=30)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(max_length=10)),
                ("photo_url", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "students",
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ingrese el nombre del Profesor", max_length=50
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Ingrese el apellido del Profesor", max_length=50
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Ingrese el correo del Profesor", max_length=100
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Ingrese el numero de telefono del Profesor",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        help_text="Ingrese la especialidad del Profesor", max_length=100
                    ),
                ),
                (
                    "biography",
                    models.TextField(help_text="Ingrese la biografia del Profesor"),
                ),
                (
                    "photo_url",
                    models.CharField(
                        blank=True,
                        help_text="Ingrese la biografia del Profesor",
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
                "db_table": "teachers",
            },
        ),
    ]
