# Generated by Django 5.2.7 on 2025-11-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="email",
            field=models.CharField(
                help_text="Ingrese el Correo del Estudiante", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="last_name",
            field=models.CharField(
                help_text="Ingrese el apellido del Estudiante", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="name",
            field=models.CharField(
                help_text="Ingrese el nombre del Estudiante", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Ingrese el numero de telefono del Estudiante",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="photo_url",
            field=models.CharField(
                blank=True,
                help_text="Ingrese el URL de la foto del Estudiante",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="state",
            field=models.CharField(
                choices=[
                    ("ACTIVO", "Activo"),
                    ("INACTIVO", "Inactivo"),
                    ("SUSPENDIDO", "suspendido"),
                ],
                help_text="Indique el estado del Estudiante",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="photo_url",
            field=models.CharField(
                blank=True,
                help_text="Ingrese la URL de la foto del Profesor",
                max_length=250,
                null=True,
            ),
        ),
    ]
