# Generated by Django 5.2.7 on 2025-11-05 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("type", models.CharField(blank=True, max_length=9, null=True)),
                ("date", models.DateTimeField()),
                ("is_moderated", models.IntegerField(blank=True, null=True)),
                ("is_active", models.IntegerField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione el curso",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courses",
                    ),
                ),
            ],
            options={
                "verbose_name": "forum",
                "verbose_name_plural": "forums",
                "db_table": "forums",
            },
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("publications_date", models.DateTimeField()),
                (
                    "attachment_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_question", models.IntegerField(blank=True, null=True)),
                ("is_accepted_answer", models.IntegerField(blank=True, null=True)),
                ("upvotes", models.IntegerField(blank=True, null=True)),
                ("downvotes", models.IntegerField(blank=True, null=True)),
                ("is_moderated", models.IntegerField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione el foro",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.forums",
                    ),
                ),
                (
                    "post_father",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione el posts",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.posts",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione el estudiante",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.students",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione el ptofesor",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teachers",
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "db_table": "posts",
            },
        ),
    ]
