# Generated by Django 5.2.7 on 2025-11-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forums",
            name="date",
            field=models.DateTimeField(help_text="Digite la fecha y hora del Foro"),
        ),
        migrations.AlterField(
            model_name="forums",
            name="description",
            field=models.TextField(help_text="Describa el tema principal del foro"),
        ),
        migrations.AlterField(
            model_name="forums",
            name="is_active",
            field=models.IntegerField(
                blank=True,
                help_text="Indique si el foro está activo o desactivado",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="forums",
            name="is_moderated",
            field=models.BooleanField(
                blank=True,
                help_text="Indique si los mensajes en el foro deben aprobarse antes de publicarse",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="forums",
            name="title",
            field=models.CharField(
                help_text="Digite el titulo del Foro", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="forums",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GENERAL", "General"),
                    ("QUESTIONS", "Questions"),
                    ("PROJECTS", "Projects"),
                    ("SOCIAL", "Social"),
                ],
                help_text="Seleccione el tipo de foro",
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="attachment_url",
            field=models.CharField(
                blank=True,
                help_text="URL del archivo adjunto (si aplica)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="content",
            field=models.TextField(help_text="Digite el Contenido del post o mensaje"),
        ),
        migrations.AlterField(
            model_name="posts",
            name="downvotes",
            field=models.IntegerField(
                default=0,
                help_text="Digite Número de votos negativos que ha recibido el post",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="edited_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha de la última edición del post",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="is_accepted_answer",
            field=models.IntegerField(
                default=False,
                help_text="Indique si la respuesta ha sido aceptada como solución",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="is_moderated",
            field=models.IntegerField(
                default=False,
                help_text="Indique si el post está pendiente de aprobación",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="is_question",
            field=models.IntegerField(
                default=False, help_text="Indique si este post es una pregunta"
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="publications_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Digite Fecha y hora en que se creó el post",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="published_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Fecha de publicación del post", null=True
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="upvotes",
            field=models.IntegerField(
                default=0,
                help_text="Digite Número de votos positivos que ha recibido el post",
            ),
        ),
    ]
