# Generated by Django 5.2.7 on 2025-11-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_forums_date_alter_forums_description_and_more"),
        ("users", "0002_alter_students_email_alter_students_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forums",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Digite la fecha y hora del Foro"
            ),
        ),
        migrations.AlterField(
            model_name="forums",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indique si el foro está activo o desactivado",
            ),
        ),
        migrations.AlterField(
            model_name="forums",
            name="is_moderated",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indique si los mensajes en el foro deben aprobarse antes de publicarse",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="is_accepted_answer",
            field=models.BooleanField(
                default=False,
                help_text="Indique si la respuesta ha sido aceptada como solución",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="is_moderated",
            field=models.BooleanField(
                default=False,
                help_text="Indique si el post está pendiente de aprobación",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="is_question",
            field=models.BooleanField(
                default=False, help_text="Indique si este post es una pregunta"
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Seleccione el profesor",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.teachers",
            ),
        ),
    ]
