# Generated by Django 5.2.7 on 2025-11-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_forums_date_alter_forums_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forums",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GENERAL", "General"),
                    ("PREGUNTA", "Pregunta"),
                    ("PROJECTOS", "Projectos"),
                    ("SOCIAL", "Social"),
                ],
                help_text="Seleccione el tipo de foro",
                max_length=9,
                null=True,
            ),
        ),
    ]
