# Generated by Django 5.2.7 on 2025-11-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(
                help_text="Ingrese el nombre del Tag", max_length=30
            ),
        ),
    ]
