# Generated by Django 5.2.7 on 2025-11-05 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliveries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("limit_date", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Seleccione la entrega",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.lessons",
                    ),
                ),
            ],
            options={
                "verbose_name": "deliverie",
                "verbose_name_plural": "deliveries",
                "db_table": "deliveries",
            },
        ),
        migrations.CreateModel(
            name="Evaluations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("type", models.CharField(max_length=10)),
                ("maximun_score", models.IntegerField(blank=True, null=True)),
                ("limit_date", models.DateTimeField(blank=True, null=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("show_results", models.IntegerField(blank=True, null=True)),
                (
                    "minimum_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("attempts_allowed", models.IntegerField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Seleccione la leccion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.lessons",
                    ),
                ),
            ],
            options={
                "verbose_name": "evaluation",
                "verbose_name_plural": "evaluations",
                "db_table": "evaluations",
            },
        ),
        migrations.CreateModel(
            name="Attempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_date", models.DateTimeField()),
                ("attempt_number", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("time_spent", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(max_length=11)),
                ("maximun_score", models.IntegerField(blank=True, null=True)),
                (
                    "score_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=5, null=True
                    ),
                ),
                ("answers", models.JSONField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione el estudiante",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.students",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione la evaluacion",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluations",
                    ),
                ),
            ],
            options={
                "verbose_name": "attempt",
                "verbose_name_plural": "attempts",
                "db_table": "attempts",
            },
        ),
        migrations.CreateModel(
            name="StudentDeliveries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("archive", models.CharField(max_length=255)),
                ("calification", models.FloatField()),
                ("state", models.CharField(max_length=20)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione la entrega",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.deliveries",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seleccione el estudiante",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.students",
                    ),
                ),
            ],
            options={
                "verbose_name": "student_deliverie",
                "verbose_name_plural": "student_deliveries",
                "db_table": "student_deliveries",
            },
        ),
    ]
