# Generated by Django 5.2.7 on 2025-11-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_courses_certificate_available_and_more"),
        ("evaluations", "0001_initial"),
        ("users", "0002_alter_students_email_alter_students_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempts",
            name="answers",
            field=models.JSONField(
                blank=True,
                help_text="Ingrese las respuestas dadas por el estudiante (en formato JSON)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="attempt_date",
            field=models.DateTimeField(help_text="Ingrese la fecha y hora del intento"),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="attempt_number",
            field=models.IntegerField(
                blank=True, help_text="Ingrese el número del intento", null=True
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Ingrese la fecha y hora de finalización del intento",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="evaluation",
            field=models.ForeignKey(
                blank=True,
                help_text="Seleccione la evaluacion relacionada con el intento",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluations.evaluations",
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="maximun_score",
            field=models.IntegerField(
                blank=True,
                help_text="Ingrese la calificación máxima del intento",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="score_obtained",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Ingrese la calificación obtenida en el intento",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Ingrese la fecha y hora de inicio del intento",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="state",
            field=models.CharField(
                choices=[
                    ("EN PROGRESO", "en progreso"),
                    ("COMPLETADO", "completado"),
                    ("CALIFICADO", "calificado"),
                ],
                help_text="Ingrese el estado del intento (ej. completado, en progreso)",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Seleccione el estudiante que realizo el intento",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.students",
            ),
        ),
        migrations.AlterField(
            model_name="attempts",
            name="time_spent",
            field=models.IntegerField(
                blank=True,
                help_text="Ingrese el tiempo total dedicado al intento (en minutos)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="description",
            field=models.TextField(help_text="Ingrese la descripción de la entrega"),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="lesson",
            field=models.ForeignKey(
                help_text="Seleccione la lección relacionada con la entrega",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.lessons",
            ),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="limit_date",
            field=models.DateTimeField(
                blank=True, help_text="Ingrese la fecha límite de la entrega", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveries",
            name="title",
            field=models.TextField(help_text="Ingrese el título de la entrega"),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="attempts_allowed",
            field=models.IntegerField(
                blank=True,
                help_text="Ingrese el número máximo de intentos permitidos",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="available_from",
            field=models.DateTimeField(
                blank=True,
                help_text="Ingrese la fecha desde la cual estará disponible la evaluación",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="available_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Ingrese la fecha hasta la cual estará disponible la evaluación",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="description",
            field=models.TextField(help_text="Ingrese la descripción de la evaluación"),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="limit_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Ingrese la fecha límite para completar la evaluación",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="maximun_score",
            field=models.IntegerField(
                blank=True,
                help_text="Ingrese la calificación máxima posible",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="minimum_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ingrese la calificación mínima para aprobar la evaluación",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="show_results",
            field=models.BooleanField(
                blank=True,
                help_text="Indique si se muestran los resultados inmediatamente",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="title",
            field=models.CharField(
                help_text="Ingrese el título de la evaluación", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXAM", "exam"),
                    ("QUIZ", "quiz"),
                    ("ASSIGNMENT", "assignment"),
                ],
                help_text="Ingrese el tipo de evaluación (ej. Quiz, Tarea, Examen)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="studentdeliveries",
            name="archive",
            field=models.CharField(
                help_text="Ingrese la URL o ruta del archivo entregado por el estudiante",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="studentdeliveries",
            name="calification",
            field=models.FloatField(
                help_text="Ingrese la calificación obtenida en la entrega"
            ),
        ),
        migrations.AlterField(
            model_name="studentdeliveries",
            name="delivery",
            field=models.ForeignKey(
                blank=True,
                help_text="Seleccione la entrega relacionada",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluations.deliveries",
            ),
        ),
        migrations.AlterField(
            model_name="studentdeliveries",
            name="delivery_date",
            field=models.DateField(
                help_text="Ingrese la fecha en que el estudiante realizó la entrega"
            ),
        ),
        migrations.AlterField(
            model_name="studentdeliveries",
            name="state",
            field=models.CharField(
                choices=[
                    ("CALIFICADO", "Calificado"),
                    ("PENDIENTE", "Pendiente"),
                    ("DEVUELTA", "Devuelta"),
                ],
                help_text="Indique el estado de la entrega",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentdeliveries",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Seleccione el estudiante que realizó la entrega",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.students",
            ),
        ),
    ]
