# Generated by Django 5.2.7 on 2025-11-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "evaluations",
            "0002_alter_attempts_answers_alter_attempts_attempt_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluations",
            name="type",
            field=models.CharField(
                choices=[
                    ("Exam", "Exam"),
                    ("Quiz", "Quiz"),
                    ("Assigment", "Assignment"),
                ],
                help_text="Ingrese el tipo de evaluación (ej. Quiz, Tarea, Examen)",
                max_length=10,
            ),
        ),
    ]
