# Generated by Django 5.2.7 on 2025-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0003_alter_evaluations_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdeliveries",
            name="delivery_date",
            field=models.DateTimeField(
                help_text="Ingrese la fecha en que el estudiante realizó la entrega"
            ),
        ),
    ]
