# Generated by Django 5.2.7 on 2025-11-05 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tituloCurso",
                    models.CharField(
                        help_text="Ingrese el titulo del Curso", max_length=200
                    ),
                ),
                (
                    "descripcionCurso",
                    models.TextField(help_text="Ingrese la descripcion del Curso"),
                ),
                (
                    "objetivoscurso",
                    models.TextField(help_text="Ingrese los objetivos del Curso"),
                ),
                (
                    "fecha_creacionCurso",
                    models.DateField(
                        help_text="Ingrese la fecha de creacion del Curso"
                    ),
                ),
                (
                    "fecha_inicioCurso",
                    models.DateField(help_text="Ingrese la fecha de inicio del Curso"),
                ),
                (
                    "fecha_finalizacionCurso",
                    models.DateField(
                        help_text="Ingrese la fecha de finalizacion del Curso"
                    ),
                ),
                (
                    "estadoCurso",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("archivado", "Archivado"),
                        ],
                        help_text="Selecciona el estado del Curso",
                        max_length=100,
                    ),
                ),
                (
                    "requerimientosCourse",
                    models.CharField(
                        blank=True,
                        help_text="Ingrese los requerimientos del curso",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Ingrese el idioma del curso", max_length=15
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Ingrese el precio del curso",
                        max_digits=10,
                    ),
                ),
                (
                    "max_students",
                    models.IntegerField(
                        blank=True,
                        help_text="Ingrese el maximo de estudiantes del curso",
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("básico", "Básico"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                        ],
                        help_text="Seleccione el nivel del curso",
                        max_length=15,
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Ingrese una imagen para el curso",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "certificate_available",
                    models.BooleanField(
                        default=False,
                        help_text="Ingrese si tiene cetificado disponible el curso",
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, help_text="Ingrese la duracion del curso", null=True
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        help_text="Seleccione el profesor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teachers",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Modules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("order", models.CharField(max_length=100)),
                ("estimated_duration", models.IntegerField(blank=True, null=True)),
                ("available_date", models.DateField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Seleccione el curso",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courses",
                    ),
                ),
            ],
            options={
                "verbose_name": "module",
                "verbose_name_plural": "modules",
                "db_table": "modules",
            },
        ),
        migrations.CreateModel(
            name="Lessons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("content_type", models.CharField(max_length=14)),
                ("available_date", models.DateField(blank=True, null=True)),
                ("order", models.CharField(max_length=50)),
                (
                    "resource_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_module",
                    models.ForeignKey(
                        help_text="Seleccione el modulo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.modules",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
                "db_table": "lessons",
            },
        ),
        migrations.CreateModel(
            name="Registrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateTimeField()),
                ("state", models.CharField(max_length=10)),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("certificate_issued", models.IntegerField(blank=True, null=True)),
                (
                    "progress",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Seleccione el curso",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courses",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Seleccione el estudiante",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.students",
                    ),
                ),
            ],
            options={
                "verbose_name": "registration",
                "verbose_name_plural": "registrations",
                "db_table": "registrations",
            },
        ),
    ]
