# Generated by Django 5.2.7 on 2025-11-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Seleccione los tags asociados al curso",
                related_name="courses",
                to="tags.tags",
            ),
        ),
    ]
