# Generated by Django 5.2.7 on 2025-11-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_courses_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses",
            old_name="fecha_creacionCurso",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="courses",
            old_name="descripcionCurso",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="courses",
            old_name="fecha_finalizacionCurso",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="courses",
            old_name="objetivoscurso",
            new_name="objetives",
        ),
        migrations.RenameField(
            model_name="courses",
            old_name="requerimientosCourse",
            new_name="requeriments",
        ),
        migrations.RenameField(
            model_name="courses",
            old_name="fecha_inicioCurso",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="courses",
            old_name="estadoCurso",
            new_name="state_course",
        ),
        migrations.RenameField(
            model_name="courses",
            old_name="tituloCurso",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="lessons",
            name="available_date",
            field=models.DateField(
                blank=True,
                help_text="Ingrese la fecha de disponibilidad de la lección",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="content",
            field=models.TextField(help_text="Ingrese el contenido de la lección"),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="content_type",
            field=models.CharField(
                help_text="Ingrese el tipo de contenido", max_length=14
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="name",
            field=models.CharField(
                help_text="Ingrese el nombre de la lección", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="order",
            field=models.CharField(
                help_text="Ingrese el orden de la lección dentro del módulo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="resource_url",
            field=models.CharField(
                blank=True,
                help_text="Ingrese la URL del recurso asociado",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="modules",
            name="available_date",
            field=models.DateField(
                blank=True,
                help_text="Ingrese la fecha de disponibilidad del Modulo",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="modules",
            name="description",
            field=models.TextField(help_text="Ingrese la descripcion del Modulo"),
        ),
        migrations.AlterField(
            model_name="modules",
            name="estimated_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Ingrese la duracion estimada del Modulo",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="modules",
            name="name",
            field=models.CharField(
                help_text="Ingrese el nombre del Modulo", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="modules",
            name="order",
            field=models.CharField(
                help_text="Ingrese el orden del Modulo", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="registrations",
            name="certificate_issued",
            field=models.BooleanField(
                blank=True, help_text="Indique si se emitió el certificado", null=True
            ),
        ),
        migrations.AlterField(
            model_name="registrations",
            name="final_grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ingrese la calificación final del estudiante",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registrations",
            name="progress",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ingrese el progreso del estudiante en el curso en porcentaje",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registrations",
            name="registration_date",
            field=models.DateTimeField(help_text="Ingrese la fecha y hora de registro"),
        ),
        migrations.AlterField(
            model_name="registrations",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Activo"),
                    ("completed", "Completado"),
                    ("cancelled", "Cancelado"),
                ],
                help_text="Seleccione el estado de la inscripción",
                max_length=10,
            ),
        ),
    ]
