# Generated by Django 5.2.7 on 2025-11-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_rename_fecha_creacioncurso_courses_creation_date_and_more"),
        ("users", "0002_alter_students_email_alter_students_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="certificate_available",
            field=models.BooleanField(
                default=False,
                help_text="Indique si tiene cetificado disponible el curso",
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="creation_date",
            field=models.DateField(
                auto_created=True, help_text="Ingrese la fecha de creacion del Curso"
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="teacher_id",
            field=models.ForeignKey(
                help_text="Seleccione el profesor asociado al curso",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.teachers",
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="id_module",
            field=models.ForeignKey(
                help_text="Seleccione el Modulo",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.modules",
            ),
        ),
        migrations.AlterField(
            model_name="modules",
            name="course",
            field=models.ForeignKey(
                help_text="Seleccione el Curso asociado al Modulo",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courses",
            ),
        ),
        migrations.AlterField(
            model_name="registrations",
            name="registration_date",
            field=models.DateTimeField(
                help_text="Ingrese la fecha y hora de la Inscripcion"
            ),
        ),
        migrations.AlterField(
            model_name="registrations",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Activo"),
                    ("completed", "Completado"),
                    ("cancelled", "Cancelado"),
                ],
                help_text="Seleccione el estado de la Inscripcion",
                max_length=10,
            ),
        ),
    ]
