# Generated by Django 5.2.7 on 2025-11-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_courses_certificate_available_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses",
            old_name="teacher_id",
            new_name="teacher",
        ),
        migrations.RenameField(
            model_name="lessons",
            old_name="id_module",
            new_name="module",
        ),
    ]
