# Generated by Django 5.2.7 on 2025-11-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_rename_teacher_id_courses_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("Texto", "TEXTO"),
                    ("Video", "VIDEO"),
                    ("PDF", "PDF"),
                    ("Enlace externo", "ENLACE EXTERNO"),
                    ("Quiz", "QUIZ"),
                    ("Documento", "DOCUMENTO"),
                ],
                help_text="Ingrese el tipo de contenido",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="modules",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Seleccione el Curso asociado al Modulo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courses",
            ),
        ),
        migrations.AlterField(
            model_name="modules",
            name="description",
            field=models.TextField(
                blank=True, help_text="Ingrese la descripcion del Modulo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="modules",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Ingrese el nombre del Modulo",
                max_length=50,
                null=True,
            ),
        ),
    ]
