# Generated by Django 5.2.7 on 2025-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_lessons_content_type_alter_modules_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="level",
            field=models.CharField(
                choices=[
                    ("BASICO", "Básico"),
                    ("INTERMEDIO", "Intermedio"),
                    ("AVANZADO", "Avanzado"),
                ],
                help_text="Seleccione el nivel del curso",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="state_course",
            field=models.CharField(
                choices=[
                    ("ACTIVO", "Activo"),
                    ("INACTIVO", "Inactivo"),
                    ("ARCHIVADO", "Archivado"),
                ],
                help_text="Selecciona el estado del Curso",
                max_length=100,
            ),
        ),
    ]
